"use client";

import { MagicStar as Sparkles } from "@/components/ui/magic-star";
import { useEffect, useState } from "react";
import { useAuthStore } from "@/stores/auth-store";
import { driver } from "driver.js";
import "driver.js/dist/driver.css";
import { LayoutDashboard, BrainCircuit, Folder, MessageSquareText, ChevronRight } from "lucide-react";
import { AnimatePresence, motion } from "framer-motion";

const MOBILE_STEPS = [
  {
    icon: Sparkles,
    title: "Welcome to Gradelys!",
    description: "This is your main dashboard. Let's discover all the features!"
  },
  {
    icon: LayoutDashboard,
    title: "Quick Tools",
    description: "Scan documents, find your notes, and track your daily progress from the menu."
  },
  {
    icon: BrainCircuit,
    title: "The Studio",
    description: "Automatically generate flashcards, quizzes, and mind maps from your courses."
  },
  {
    icon: Folder,
    title: "Your Spaces",
    description: "Create spaces for each subject. The AI will remember everything you upload (PDFs, videos)."
  },
  {
    icon: MessageSquareText,
    title: "Chat with AI",
    description: "Ask questions, upload files, and search the web. The AI will answer you!"
  }
];

export function OnboardingTour() {
  const initialized = useAuthStore((s) => s.initialized);
  const user = useAuthStore((s) => s.user);

  const [isMobile, setIsMobile] = useState(false);
  const [showMobileModal, setShowMobileModal] = useState(false);
  const [mobileStep, setMobileStep] = useState(0);

  useEffect(() => {
    if (initialized && user) {
      const hasSeen = localStorage.getItem("gradelys:onboarding_completed");
      
      // Bypasser le tour si l'utilisateur a déjà complété son onboarding de profil dans la base de données
      // (ex: connexion sur un nouvel appareil ou données locales supprimées)
      if (user.learningProfile?.onboardingCompleted && !hasSeen) {
        localStorage.setItem("gradelys:onboarding_completed", "true");
        return;
      }

      if (!hasSeen) {
        if (window.innerWidth < 768) {
          setIsMobile(true);
          setShowMobileModal(true);
        } else {
          // Let the UI render completely first
          const timeout = setTimeout(() => {
            let handleKeyDown: (e: KeyboardEvent) => void;

            const driverObj = driver({
              showProgress: true,
              nextBtnText: 'Next ↵',
              prevBtnText: '← Previous',
              doneBtnText: 'Let\'s go! ↵',
              allowClose: true,
              overlayColor: 'rgba(15, 23, 42, 0.7)',
              popoverClass: 'gradelys-tour-popover',
              steps: [
                {
                  element: '#tour-logo',
                  popover: {
                    title: '<div class="flex items-center gap-2 text-xl font-bold text-primary"><span class="text-2xl">✨</span> Welcome to Gradelys!</div>',
                    description: '<div class="text-slate-500 mt-2 text-[15px] leading-relaxed">This is your main dashboard. Follow the guide to discover all features!</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-switcher',
                  popover: {
                    title: '<div class="font-bold text-lg">Browse or Chat 🔄</div>',
                    description: '<div class="text-slate-500 mt-1">Easily switch between exploring your documents and chatting with the AI.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-scan',
                  popover: {
                    title: '<div class="font-bold text-lg">Scan 📄</div>',
                    description: '<div class="text-slate-500 mt-1">Digitize your paper documents and transform them into smart text in one click.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-notes',
                  popover: {
                    title: '<div class="font-bold text-lg">Your Notes 📝</div>',
                    description: '<div class="text-slate-500 mt-1">Find all notes and summaries generated by the AI for you.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-progress',
                  popover: {
                    title: '<div class="font-bold text-lg">Your Progress 📈</div>',
                    description: '<div class="text-slate-500 mt-1">Track your statistics, learning streak, and quiz scores.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-recent-activity',
                  popover: {
                    title: '<div class="font-bold text-lg">Recent Activity 🕒</div>',
                    description: '<div class="text-slate-500 mt-1">Quickly resume your latest conversations where you left off.</div>',
                    side: 'left',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-quick-stats',
                  popover: {
                    title: '<div class="font-bold text-lg">Quick Stats 📊</div>',
                    description: '<div class="text-slate-500 mt-1">A quick overview of your activity: messages, documents, quizzes, and notes created.</div>',
                    side: 'left',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-studio',
                  popover: {
                    title: '<div class="font-bold text-lg">Welcome to the Studio 🎨</div>',
                    description: '<div class="text-slate-500 mt-1">This is where you can transform your courses into interactive learning tools.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-practice',
                  popover: {
                    title: '<div class="font-bold text-lg">Practice (Flashcards & Quiz) 🧠</div>',
                    description: '<div class="text-slate-500 mt-1">The AI generates custom flashcards and quizzes to test you on your documents.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-visualize',
                  popover: {
                    title: '<div class="font-bold text-lg">Visualize 🗺️</div>',
                    description: '<div class="text-slate-500 mt-1">Automatically create mind maps and diagrams from any course.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-studio-item',
                  popover: {
                    title: '<div class="font-bold text-lg">The Creative Studio ✨</div>',
                    description: '<div class="text-slate-500 mt-1">Generate structured summaries, revision sheets, and much more.</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-spaces',
                  popover: {
                    title: '<div class="font-bold text-lg">Your Spaces 📁</div>',
                    description: '<div class="text-slate-500 mt-1">Create spaces for each subject to organize your courses (PDFs, videos).</div>',
                    side: 'right',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-active-space',
                  popover: {
                    title: '<div class="font-bold text-lg">Active Space 🎯</div>',
                    description: '<div class="text-slate-500 mt-1">Select a space so the AI ONLY searches for answers in those documents.</div>',
                    side: 'left',
                    align: 'start'
                  }
                },
                {
                  element: '#tour-chat-input',
                  popover: {
                    title: '<div class="font-bold text-lg">Chat with AI 🚀</div>',
                    description: '<div class="text-slate-500 mt-1">Ask all your questions here. The AI will answer based on your documents!</div>',
                    side: 'top',
                    align: 'center'
                  }
                },
                {
                  element: '#tour-file-upload',
                  popover: {
                    title: '<div class="font-bold text-lg">Upload a File 📎</div>',
                    description: '<div class="text-slate-500 mt-1">Click here to quickly upload a PDF or image for the AI to analyze.</div>',
                    side: 'top',
                    align: 'center'
                  }
                },
                {
                  element: '#tour-web-search',
                  popover: {
                    title: '<div class="font-bold text-lg">Web Search 🌐</div>',
                    description: '<div class="text-slate-500 mt-1">Enable this if you want the AI to search the internet for fresh answers. You are ready! 🎉</div>',
                    side: 'top',
                    align: 'end'
                  }
                }
              ],
              onDestroyed: () => {
                document.removeEventListener('keydown', handleKeyDown);
                localStorage.setItem("gradelys:onboarding_completed", "true");
              }
            });

            handleKeyDown = (e: KeyboardEvent) => {
              if (e.key === 'Enter' || e.key === ' ') {
                if (e.target instanceof HTMLInputElement || e.target instanceof HTMLTextAreaElement) return;
                e.preventDefault();
                if (driverObj.hasNextStep()) driverObj.moveNext();
                else driverObj.destroy();
              }
            };

            document.addEventListener('keydown', handleKeyDown);
            driverObj.drive();
          }, 800);

          return () => clearTimeout(timeout);
        }
      }
    }
  }, [initialized, user]);

  const completeMobileTour = () => {
    setShowMobileModal(false);
    localStorage.setItem("gradelys:onboarding_completed", "true");
  };

  const nextMobileStep = () => {
    if (mobileStep < MOBILE_STEPS.length - 1) {
      setMobileStep((prev) => prev + 1);
    } else {
      completeMobileTour();
    }
  };

  if (isMobile && showMobileModal) {
    const CurrentStep = MOBILE_STEPS[mobileStep];
    const Icon = CurrentStep.icon;

    return (
      <div className="fixed inset-0 z-[9999] flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
        <motion.div 
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="relative w-full max-w-[360px] overflow-hidden rounded-3xl bg-white p-6 shadow-2xl"
        >
          {/* Step indicators */}
          <div className="mb-8 flex justify-center gap-2">
            {MOBILE_STEPS.map((_, i) => (
              <div
                key={i}
                className={`h-1.5 rounded-full transition-all duration-300 ${
                  i === mobileStep ? "w-8 bg-primary" : "w-2 bg-slate-200"
                }`}
              />
            ))}
          </div>

          <div className="relative min-h-[220px]">
            <AnimatePresence mode="wait">
              <motion.div
                key={mobileStep}
                initial={{ opacity: 0, x: 20 }}
                animate={{ opacity: 1, x: 0 }}
                exit={{ opacity: 0, x: -20 }}
                transition={{ duration: 0.3, ease: "easeOut" }}
                className="absolute inset-0 flex flex-col items-center text-center"
              >
                <div className="mb-6 flex h-20 w-20 items-center justify-center rounded-2xl bg-[var(--primary-subtle)]">
                  <Icon className="h-10 w-10 text-primary" />
                </div>
                <h2 className="mb-3 text-2xl font-bold text-slate-800 tracking-tight">
                  {CurrentStep.title}
                </h2>
                <p className="text-[15px] leading-relaxed text-slate-500">
                  {CurrentStep.description}
                </p>
              </motion.div>
            </AnimatePresence>
          </div>

          <button
            onClick={nextMobileStep}
            className="mt-6 flex w-full items-center justify-center rounded-xl bg-primary py-4 text-base font-semibold text-white shadow-lg shadow-primary/30 transition-transform active:scale-[0.98]"
          >
            {mobileStep === MOBILE_STEPS.length - 1 ? "Let's go!" : "Next"}
            {mobileStep < MOBILE_STEPS.length - 1 && <ChevronRight className="ml-1 h-5 w-5" />}
          </button>
        </motion.div>
      </div>
    );
  }

  return null;
}

